news_search_project/news_search_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search_articles, name='search_articles'),
    path('results/', views.results, name='results'),
    path('show/', views.show, name='show'),
    ]

news_search_project/news_search_project/urls.py
# from django.contrib import admin
# from django.urls import path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
from django.contrib import admin
from django.urls import path,include
from news_search_app import views

urlpatterns = [
    path('',include('news_search_app.urls')),
    path('admin/',admin.site.urls),  # Define this line for the 'results' view
]

news_search_project/news_search_app/models.py
from django.db import models

class Keyword(models.Model):
    keyword = models.CharField(max_length=255)

class Search(models.Model):
    keyword = models.ForeignKey(Keyword, on_delete=models.CASCADE)
    search_time = models.DateTimeField(auto_now_add=True)

class Article(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    publication_date = models.DateTimeField()
    search = models.ForeignKey(Search, on_delete=models.CASCADE)

news_search_project/news_search_app/views.py
from django.shortcuts import render
from .models import Keyword, Search, Article
from .utils import fetch_articles


def search_articles(request):
    # if request.method == "GET":
    #     keyword_text = request.POST.get("keyword")
    #     keyword, created = Keyword.objects.get_or_create(keyword=keyword_text)
    #
    #     search = Search.objects.create(keyword=keyword)
    #     articles = fetch_articles(keyword_text)
    #
    #     for article_data in articles:
    #         Article.objects.create(
    #             title=article_data["title"],
    #             url=article_data["url"],
    #             publication_date=article_data["publishedAt"],
    #             search=search
    #         )

        return render(request, "search.html")


def results(request):
    searches = Search.objects.all()
    return render(request, "results.html", {"searches": searches})

def show(request):
    return render(request,"show.html")

news_search_project/news_search_app/templates/results.html
<!DOCTYPE html>
<html>
<head>
    <title>Search Results</title>
</head>
<body>
    <h1>Search Results</h1>
    <ul>
        {% for search in searches %}
        <li>
            <strong>{{ search.keyword }}</strong> - {{ search.search_time }}
            <ul>
                {% for article in search.article_set.all %}
                <li><a href="{{ article.url }}" target="_blank">{{ article.title }}</a></li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

news_search_project/news_search_app/templates/search.html
<!DOCTYPE html>
<html>
<head>
    <title>News Search</title>
</head>
<body>
    <h1>Search for News Articles</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="keyword" placeholder="Enter a keyword">
        <button type="submit">Search</button>
    </form>
</body>
</html>

news_search_project/news_search_app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h5>i am in </h5>
</body>
</html>